## Creating Numpy Arrays

In [27]:
import numpy as np

In [28]:
# Vector
a=np.array([1,2,3])
a

array([1, 2, 3])

In [29]:
type(a)

numpy.ndarray

In [30]:
# Matrix
b=np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# Tensor
c=np.array([[[1,2,3], [4,5,6]], [[4,3,2], [1,9,0]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 3, 2],
        [1, 9, 0]]])

In [32]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [33]:
np.array([1,2,3], dtype=bool)

array([ True,  True,  True])

In [34]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [35]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [36]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [37]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.random.random((3,4))

array([[0.55876457, 0.15212595, 0.86345713, 0.62270759],
       [0.30170105, 0.82873623, 0.64900421, 0.66397848],
       [0.88025741, 0.12448593, 0.83871881, 0.99968724]])

In [40]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [114]:
np.linspace(10,100,10, dtype=int)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [41]:
np.linspace(-10,10,10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [42]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Array Attributes

In [115]:
a1=np.arange(10, dtype=np.int32)
a2=np.arange(12, dtype=float).reshape(4,3)
a3=np.arange(8).reshape(2,2,2)

print(a1)
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [116]:
a3.ndim

3

In [117]:
a2.shape

(4, 3)

In [118]:
a3.shape

(2, 2, 2)

In [119]:
a2.size

12

In [120]:
a3.size

8

In [121]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [122]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


## Changing DataTypes

In [126]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [127]:
a3.dtype

dtype('int64')

## Array Operations

In [128]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)

print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [129]:
## Scalar Operations
# Arithmetic Operations

a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [130]:
a2**2

array([[144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [131]:
## Relational Operations
a1==15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [132]:
a1==10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [133]:
a2>=20

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [134]:
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [135]:
## Vector Operations
# Arithmetic Operations
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [136]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [137]:
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

## Array Functions

In [138]:
## min, max, sum, prod
a1= np.random.random((3,3))
a1= np.round(a1*100)
a1

array([[15., 84., 29.],
       [86., 90., 19.],
       [66.,  3., 72.]])

In [139]:
np.max(a1)

np.float64(90.0)

In [140]:
np.min(a1)

np.float64(3.0)

In [141]:
np.sum(a1)

np.float64(464.0)

In [142]:
np.prod(a1)

np.float64(76605648134400.0)

In [143]:
# 0-> col and 1-> row
np.min(a1, axis=1)

array([15., 19.,  3.])

In [144]:
np.max(a1, axis=1)

array([84., 90., 72.])

In [145]:
np.sum(a1, axis=1)

array([128., 195., 141.])

In [146]:
np.prod(a1, axis=1)

array([ 36540., 147060.,  14256.])

In [147]:
## mean, median, std, var 
np.mean(a1, axis=1)

array([42.66666667, 65.        , 47.        ])

In [148]:
np.median(a1, axis=1)

array([29., 86., 66.])

In [149]:
np.std(a1, axis=1)

array([29.78067979, 32.56787783, 31.20897307])

In [150]:
np.var(a1, axis=1)

array([ 886.88888889, 1060.66666667,  974.        ])

In [151]:
## trigonometric functions
np.sin(a1)

array([[ 0.65028784,  0.73319032, -0.66363388],
       [-0.92345845,  0.89399666,  0.14987721],
       [-0.02655115,  0.14112001,  0.25382336]])

In [152]:
## dot product
a2= np.arange(12).reshape(3,4)
a3= np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [100]:
## log and exponents
np.exp(a1)

array([[4.85165195e+08, 4.92345829e+41, 4.31123155e+15],
       [3.40427605e+29, 2.03828107e+34, 6.23514908e+27],
       [1.85867175e+31, 2.58131289e+20, 1.22040329e+39]])

In [101]:
np.log(a1)

array([[2.99573227, 4.56434819, 3.58351894],
       [4.21950771, 4.36944785, 4.15888308],
       [4.27666612, 3.8501476 , 4.49980967]])

In [109]:
## round, floor, ceil
## round, floor, ceil

a3= np.random.random((2,3))*100
a3

array([[45.35349153, 89.35813104, 61.51046589],
       [23.80478806, 80.25251981, 46.80194224]])

In [110]:
np.round(a3)

array([[45., 89., 62.],
       [24., 80., 47.]])

In [111]:
np.ceil(a3)

array([[46., 90., 62.],
       [24., 81., 47.]])

In [112]:
np.floor(a3)

array([[45., 89., 61.],
       [23., 80., 46.]])

## Indexing & Slicing

In [155]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [156]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [159]:
a2[1,0]

np.int64(4)

In [160]:
a3[1,0,1]

np.int64(5)

In [161]:
a3[1,1,0]

np.int64(6)

In [162]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
a1[2:5:2]

array([2, 4])

In [165]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [170]:
a2[1::,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [171]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [172]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [176]:
a2[1,::3]

array([4, 7])

In [177]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [179]:
a4=np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [180]:
a4[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [181]:
a4[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [187]:
a4[0,1,:]

array([3, 4, 5])

In [188]:
a4[0,1]

array([3, 4, 5])

In [189]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [190]:
a4[1,:,1]

array([10, 13, 16])

In [192]:
a4[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [193]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [212]:
a4[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [213]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [214]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [216]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [218]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [219]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [220]:
for i in a4:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [221]:
for i in np.nditer(a4):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [223]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [222]:
# Transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [224]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [226]:
# Ravel
a4.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [230]:
a5=np.arange(12).reshape(3,4)
a6=np.arange(12,24).reshape(3,4)

In [231]:
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [232]:
a6

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [234]:
## Horizontal Stacking
np.hstack((a5,a6,a5,a6))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [235]:
## Vertical Stacking
np.vstack((a5,a6,a5,a6))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [239]:
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [237]:
## Horizontal Splitting
np.hsplit(a5,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [238]:
np.hsplit(a5,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [242]:
a6

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [243]:
## Vertical Splitting
np.vsplit(a5,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]